from sys import argv
script, filename = argv
print(f"Vamos a eliminar {filename}.")
print("Si no quieres, presiona CTRL-C (^C).")
print("Si si , presiona RETURN.")
input("?")
print("Abriendo el documento ...")
target = open(filename, 'w')
print("Truncating the file. Goodbye!")
target.truncate()
print("Now I'm going to ask you for three lines.")
line1 = input("linea 1: ")
line2 = input("linea 2: ")
line3 = input("linea 3: ")
print("I'm going to write esto en el documento.")
target.write(line1)
target.write("\n")
target.write(line2)
target.write("\n")
target.write(line3)
target.write("\n")
print("And finalmente, terminamos it.")
target.close()